### ISSUE TITLE
Revisión del pinout para Colorlight 5A-75E Versión 7.1

### ISSUE THREAD

**Issue by johnnycubides** [unal-digital-electronic/litex-and-softcore-projects#4]
En el siguiente [Issue](https://github.com/q3k/chubby75/issues/59) se habla sobre el proceso documentar el hardware para la fpga en cuestión y comparten el siguiente pinout [Hardware colorlight 5A-75E](https://github.com/q3k/chubby75/files/4600592/hardware_V7.1.txt), es una referencia que no necesariamente funciona pero puede ser un punto de partida.

**Comment by derekmulcahy** [comment]
The file for the 5A-75E has been updated, see the comments on the other project. 

https://github.com/q3k/chubby75/issues/59

**Comment by johnnycubides** [comment]
@ejacerov podrías tener en cuenta la anterior respuesta para el desarrollo del esquemático que estás haciendo en kicad de la colorlight 5a-75e.

**Comment by johnnycubides** [comment]
> The file for the 5A-75E has been updated, see the comments on the other project.
> 
> [q3k/chubby75#59](https://github.com/q3k/chubby75/issues/59)
Thanks for your help, we have worked to test projects with color light and we have documentation in this [wiki](https://github.com/unal-digital-electronic/litex-and-softcore-projects/wiki)
